<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Complete</name>
   <tag></tag>
   <elementGuidId>fcfddca4-5a38-4b6e-b98b-6bc689aec64a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and @data-testid = 'quick-link-complete-task-btn' and (text() = 'Complete' or . = 'Complete')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.portalTenant167.portalTenant138.portalTenant146.portalTenant147</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;quick-link-complete-task-btn&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1fc8792d-51e7-41c0-afe1-c5b143a175d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portalTenant167 portalTenant138 portalTenant146 portalTenant147</value>
      <webElementGuid>df8cbec3-8b4a-4cc6-bb71-1b1e306e04fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8dbf7654-a3ce-4a54-9df9-87b05d06c598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14e4de24-f282-4556-b5c9-19f78905ef49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>quick-link-complete-task-btn</value>
      <webElementGuid>b484a15a-94ec-4596-800b-98fc8e8cdf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complete</value>
      <webElementGuid>8a1f7a88-4709-4ff3-8c76-b01d18f2638f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-portal-tenant&quot;)/div[1]/div[1]/div[@class=&quot;portalTenant26&quot;]/div[@class=&quot;portalTenant66 portalTenant30 portalTenant25&quot;]/button[@class=&quot;portalTenant167 portalTenant138 portalTenant146 portalTenant147&quot;]</value>
      <webElementGuid>6293d7c9-dc75-438e-bca0-cd0474599771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @data-testid = 'quick-link-complete-task-btn' and (text() = 'Complete' or . = 'Complete')]</value>
      <webElementGuid>81cda2e7-b29a-494d-902d-0fec819efac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='maggie.smith@testmail.com'])[2]/following::button[1]</value>
      <webElementGuid>71dabebe-af67-4241-9ab2-d7c806a1b5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorised Signatory'])[1]/following::button[1]</value>
      <webElementGuid>72868a8d-f91f-427d-b4e4-c044b49e2620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>6a78a10b-3b85-405a-ab89-95e2bc7b69af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-portal-tenant']/div/div/div/div[3]/button</value>
      <webElementGuid>413e1c0c-448a-4e74-aa64-8be6b2b38b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/button</value>
      <webElementGuid>7c60de24-bc63-49c6-ae2f-d4a258adbe69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
