<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Link</name>
   <tag></tag>
   <elementGuidId>26d7bdea-b00c-4a75-aea4-dbd5991c008f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-testid = 'fen-radio-chip-link' and (text() = 'Link' or . = 'Link')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.portalTenant167.portalTenant427.portalTenant425.portalTenant432</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-radio-chip-link&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5af1e7f5-fe73-4470-91d4-4b8dd1f85b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portalTenant167 portalTenant427 portalTenant425 portalTenant432</value>
      <webElementGuid>147ac97b-986f-4cd9-802d-adc3e6d00fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4ce901ac-dcea-4d64-b7ee-2a039ee7f47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee76aadb-31fb-4241-a3a1-f107b5237218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>fen-radio-chip-link</value>
      <webElementGuid>643bb8d3-61bd-4a9a-a9ff-53d992eff3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>8a18acb8-8273-434f-8bef-dc8258c6834f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;portalTenant301&quot;]/div[@class=&quot;portalTenant304 portalTenant302&quot;]/div[@class=&quot;portalTenant324 portalTenant305 portalTenant297 portalTenant306 portalTenant311 portalTenant314 portalTenant351 portalTenant325&quot;]/div[@class=&quot;portalTenant296&quot;]/div[@class=&quot;portalTenant489&quot;]/div[@class=&quot;portalTenant377 portalTenant488&quot;]/table[@class=&quot;portalTenant378&quot;]/tbody[@class=&quot;portalTenant415&quot;]/tr[@class=&quot;portalTenant384 portalTenant423 portalTenant416 portalTenant386&quot;]/td[@class=&quot;portalTenant389 portalTenant391 portalTenant420 portalTenant393&quot;]/div[@class=&quot;portalTenant167 portalTenant427 portalTenant425 portalTenant432&quot;]</value>
      <webElementGuid>950bbb31-3a79-48d3-a334-b3aded926839</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@data-testid = 'fen-radio-chip-link' and (text() = 'Link' or . = 'Link')]</value>
      <webElementGuid>bece2772-9b2b-446a-ae9c-7d63ae3588e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::div[2]</value>
      <webElementGuid>e026bef0-bdd5-47ba-81ef-c7be7ab40296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship'])[1]/following::div[2]</value>
      <webElementGuid>00bfad26-3f50-4403-b7e3-28201701eb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maggie Smith'])[1]/preceding::div[2]</value>
      <webElementGuid>e9891fb6-47b1-4786-91b3-320805b961c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div</value>
      <webElementGuid>135c8108-5d52-4021-99b7-18c881cbc191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Type'])[2]/following::div[2]</value>
      <webElementGuid>68f315c8-b768-4c71-839c-703f48e816c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::div[2]</value>
      <webElementGuid>1afe4b97-1cdf-4348-a7bc-18629754138b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]/div</value>
      <webElementGuid>f6b58dd4-90d7-4209-aa70-2deb1510619f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
