<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SaveComplete</name>
   <tag></tag>
   <elementGuidId>d711404d-0a3f-494d-b4b5-c2c275bd0537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-testid = 'fen-button-bar' and (text() = 'SaveComplete' or . = 'SaveComplete')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.entitydata169.entitydata182</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SaveComplete&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>acf60929-829e-4fbc-a3d7-a0723b7776fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata169 entitydata182</value>
      <webElementGuid>9b39f65a-445a-482c-a4c5-9ec1d9ba384d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>fen-button-bar</value>
      <webElementGuid>b22259da-ab72-4125-944f-a7adf0c7f5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SaveComplete</value>
      <webElementGuid>ad4ab624-1d32-49f5-bcad-e7ef3e0e03e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-entitydata&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;entitydata129&quot;]/div[@class=&quot;entitydata132 entitydata133&quot;]/div[@class=&quot;entitydata169 entitydata182&quot;]</value>
      <webElementGuid>f3894610-de06-43c3-8650-6e5b3ea4298f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@data-testid = 'fen-button-bar' and (text() = 'SaveComplete' or . = 'SaveComplete')]</value>
      <webElementGuid>ec7df639-ce16-4e6b-aea6-f2deb9f70949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[1]</value>
      <webElementGuid>8edd7a9b-0eb1-4d4f-88df-8f9d577a3cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div[2]/div[3]</value>
      <webElementGuid>f18112d5-b1c2-416d-bf5d-8c466adce7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>d087f3ba-2489-4057-a000-abc8bd3d1291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
