<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Active_portalTenant466</name>
   <tag></tag>
   <elementGuidId>17702ad0-0433-4aae-af8d-a2489dbe8585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.portalTenant389.portalTenant391.portalTenant419.portalTenant393 > span.portalTenant167.portalTenant361.portalTenant463.portalTenant558.portalTenant562.portalTenant365 > span.portalTenant369 > input.portalTenant466</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;table-body-checkbox&quot;] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d370818-681a-44ff-9ce7-651693e1b14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portalTenant466</value>
      <webElementGuid>b24b7632-b196-498b-a62a-30334d1a1dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8ae0dd15-bf04-4acd-ae78-c370bf869f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-indeterminate</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4d2dc1cb-2e74-4aee-a7df-3bbe77a1a86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-portal-tenant&quot;)/div[1]/div[1]/div[@class=&quot;portalTenant26&quot;]/div[@class=&quot;portalTenant29 portalTenant30&quot;]/div[@class=&quot;portalTenant599&quot;]/div[@class=&quot;portalTenant377 portalTenant598&quot;]/table[@class=&quot;portalTenant378&quot;]/tbody[@class=&quot;portalTenant415&quot;]/tr[@class=&quot;portalTenant384 portalTenant423 portalTenant416 portalTenant386&quot;]/td[@class=&quot;portalTenant389 portalTenant391 portalTenant419 portalTenant393&quot;]/span[@class=&quot;portalTenant167 portalTenant361 portalTenant463 portalTenant558 portalTenant562 portalTenant365&quot;]/span[@class=&quot;portalTenant369&quot;]/input[@class=&quot;portalTenant466&quot;]</value>
      <webElementGuid>7bfd8f77-b26f-4524-9b8b-67c6c184ef71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>703c777a-cab8-4d2e-b81b-350f910ca6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>863f7b83-04c3-4ba2-b265-d1fc2ea44a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-portal-tenant']/div/div/div/div[2]/div/div[3]/table/tbody/tr/td[2]/span/span/input</value>
      <webElementGuid>f4f33551-7497-4d55-b1a5-9bd311ad5fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/span/input</value>
      <webElementGuid>d12e04b8-32d0-4e0d-9f6e-e544be649185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
