<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ZipCodePostCode_properties.address_zi_d029dd</name>
   <tag></tag>
   <elementGuidId>4f6f5ed8-1144-4a41-9d55-ca544357efea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'properties.address_zipCodePostCode' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fenx-87327</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;ZipCode/PostCode*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00f5f572-3722-4877-9f55-035cf9d9efc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bac27456-2a27-401b-9094-4d7e269b0a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>properties.address_zipCodePostCode</value>
      <webElementGuid>72b9a3c9-c2c2-4bf8-b9dd-f929a70855ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2958c40-9e2b-4b39-8cc1-6d71007dd9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMarginDense MuiOutlinedInput-inputMarginDense</value>
      <webElementGuid>14f4fd66-c677-47c7-8acd-a1fb97b64cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fenx-87327</value>
      <webElementGuid>cfeaae4d-55e3-4d9c-a4c4-ee3fac7f3e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fenx-87327&quot;)</value>
      <webElementGuid>189830c9-14db-4c78-beeb-209dcb894e03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'properties.address_zipCodePostCode' and @type = 'text']</value>
      <webElementGuid>4bbee30f-350f-43f1-bf53-8166b6f8b2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fenx-87327']</value>
      <webElementGuid>f5083537-462e-4566-8c84-31cb6a5a2b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[6]/div/div[2]/div/input</value>
      <webElementGuid>86acc435-7e83-4166-a9c1-07ab3aad52fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
