<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Billing</name>
   <tag></tag>
   <elementGuidId>4202bc21-a238-47f3-92ef-fafc75fb5b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'Billing' or . = 'Billing')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fenx-19595-option-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Billing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c8909be4-353d-44fe-b6dd-332f294d05cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b25beda3-857e-4d86-9b68-1d752ab00b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>28ff50c2-f59f-47ec-ba19-789ad3b1b871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fenx-19595-option-6</value>
      <webElementGuid>39aa9c45-313a-411e-805a-70d15f2af18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2266235c-941a-4ea5-bb50-16d2e1fa5b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d6e2529-ec4c-4e1d-aee2-225ea8d9a23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db03065f-ef3e-473c-b48b-26bf2787a2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option</value>
      <webElementGuid>bc18e97a-8ac1-420a-ba4a-d9c38a2878b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8faf04c4-4089-43f5-99a0-cb85a7ccca8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Billing</value>
      <webElementGuid>99641580-aed4-4ebe-be66-22f98bc3b751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fenx-19595-option-6&quot;)</value>
      <webElementGuid>36137769-5b86-45d2-9d14-d78fd6c9f6ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Billing' or . = 'Billing')]</value>
      <webElementGuid>afbdf43a-f17c-4287-aed9-aef5ce10411b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='US BOI Reporting'])[1]/following::li[1]</value>
      <webElementGuid>2c744ed2-2be2-4675-adec-600cd97910ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/following::li[2]</value>
      <webElementGuid>7e3ccf17-6c93-4123-b941-1e25e769e47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Billing']/parent::*</value>
      <webElementGuid>0bb693d8-422f-44b0-b91e-9a011a76b8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='fenx-19595-option-6']</value>
      <webElementGuid>066d4012-1173-48d0-b75c-6b47435a7fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='fenx-19595-popup']/li[7]</value>
      <webElementGuid>5b048983-4b51-4312-a550-621a5508ac7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>0927c122-f9c0-41c1-8b59-d2cade42531f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
