<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_POC CA-MR2 Enterprise</name>
   <tag></tag>
   <elementGuidId>ccae6d11-7019-4f65-82f7-f0052127f62c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.jou502.jou3230.jou3232.jou525</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-testid = 'fen-link-poc-ca-mr2-enterprise' and @href = '/entity-data/5f3a523c-3bda-4094-bae6-f93427d61906' and (text() = 'POC CA-MR2 Enterprise' or . = 'POC CA-MR2 Enterprise')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-link-poc-ca-mr2-enterprise&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cc33933-2db9-4add-b3b7-d7d136169b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jou502 jou3230 jou3232 jou525</value>
      <webElementGuid>671e22d4-5a07-40ea-a1d9-6e5890ecbff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>fen-link-poc-ca-mr2-enterprise</value>
      <webElementGuid>5ceed94d-9f18-4014-b367-f476da29bc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/entity-data/5f3a523c-3bda-4094-bae6-f93427d61906</value>
      <webElementGuid>799b22ea-7972-44b0-b941-8dc7e9197d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>POC CA-MR2 Enterprise</value>
      <webElementGuid>f3e1cff3-a5c5-4733-86ea-6e63ea7dd762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-journey&quot;)/div[1]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;jou494&quot;]/div[@class=&quot;jou497 jou498&quot;]/div[3]/div[@class=&quot;jou3306&quot;]/div[@class=&quot;jou3191 jou3305&quot;]/table[@class=&quot;jou3192&quot;]/tbody[@class=&quot;jou3220&quot;]/tr[@class=&quot;jou3198 jou3228 jou3221 jou3200&quot;]/td[@class=&quot;jou3203 jou3205 jou3225 jou3207&quot;]/div[@class=&quot;jou3172&quot;]/a[@class=&quot;jou502 jou3230 jou3232 jou525&quot;]</value>
      <webElementGuid>76652311-e726-4054-892d-d7738169e3cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@data-testid = 'fen-link-poc-ca-mr2-enterprise' and @href = '/entity-data/5f3a523c-3bda-4094-bae6-f93427d61906' and (text() = 'POC CA-MR2 Enterprise' or . = 'POC CA-MR2 Enterprise')]</value>
      <webElementGuid>3ae7e283-e057-4d4e-83b7-42ef37d11672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Type'])[1]/following::a[1]</value>
      <webElementGuid>d1835f2e-6182-45d4-9010-742f27dfe07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Type'])[1]/following::a[1]</value>
      <webElementGuid>0b845d77-8db6-4b8a-a1e2-9fc9eac354b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exact Match'])[1]/preceding::a[1]</value>
      <webElementGuid>d6faf647-8d7d-476e-898a-02a2016838bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[2]/preceding::a[1]</value>
      <webElementGuid>fae1be1b-6b2c-401c-81af-4356cb3777f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='POC CA-MR2 Enterprise']/parent::*</value>
      <webElementGuid>cf42b5ce-2281-4b38-b55c-7aef4d612cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-journey']/div/div/div/div/div/div/div[2]/div[3]/div/div[2]/table/tbody/tr/td[2]/div/a</value>
      <webElementGuid>2be4368d-b9d4-4c93-8eeb-61f27282c2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'POC CA-MR2 Enterprise')]</value>
      <webElementGuid>f270f228-9b25-4bcd-8a73-e2717a839406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/entity-data/5f3a523c-3bda-4094-bae6-f93427d61906')]</value>
      <webElementGuid>4208de05-1ab7-459d-bc3e-7da27c85aac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a</value>
      <webElementGuid>3f45fd42-d710-4a5f-948f-9a3b88ec8a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
