<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Contact</name>
   <tag></tag>
   <elementGuidId>2e514c81-a884-4a21-9d64-ba362b2ef210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[contains(text(), 'Add Address')]//following::span[text()='Add'])[1]&#xd;
 </value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.entitydata284.entitydata372.entitydata374.entitydata2163 > span.entitydata373</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;dataGroupItemsGrid-address&quot;] >> internal:role=button[name=&quot;Add&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>387e9cb0-13c9-4c8b-ac56-8825db214df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata373</value>
      <webElementGuid>73431d41-9db3-43ef-b131-162d68498c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>d3d2bf7c-b6b4-4cf5-af43-fc324404e744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-entitydata&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;entitydata129&quot;]/div[@class=&quot;entitydata132 entitydata133&quot;]/div[4]/div[2]/div[@class=&quot;entitydata2160&quot;]/div[@class=&quot;entitydata2162&quot;]/button[@class=&quot;entitydata284 entitydata372 entitydata374 entitydata2163&quot;]/span[@class=&quot;entitydata373&quot;]</value>
      <webElementGuid>0f5ac4c4-4094-43e9-bc8b-76a6ec38ecb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>41206327-f78b-4ba2-91c6-d8574417d98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Address'])[1]/following::span[3]</value>
      <webElementGuid>d0ce83e5-e8de-474e-8e04-754585aeafc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data added'])[1]/preceding::span[5]</value>
      <webElementGuid>a52ba029-ad3b-434a-a0a9-dbf37213e91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::span[5]</value>
      <webElementGuid>96608549-fcd0-42d4-bff4-bd97f0515500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>0128eaf4-7dab-4294-9139-a034916c445d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div/div[2]/div[4]/div[2]/div/div/button/span</value>
      <webElementGuid>802fd572-c73f-4055-bddb-edbf49c4c118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/button/span</value>
      <webElementGuid>f2034e91-140b-4631-bfe4-9d29ae4a421d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div/div[2]/div[5]/div[2]/div/div/button/span</value>
      <webElementGuid>63ff2ced-18bf-46c6-9783-9f55ab7b258b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Contact'])[1]/following::span[3]</value>
      <webElementGuid>bf516cdb-6532-4bf1-a210-cbfbc976107c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data added'])[2]/preceding::span[3]</value>
      <webElementGuid>46c94d86-53cd-440b-81ba-4a66876817a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emails'])[1]/preceding::span[3]</value>
      <webElementGuid>f988e2d8-0be6-4505-9ec9-eff439a3dfac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/button/span</value>
      <webElementGuid>5cf8ab53-ecfb-4069-b0a2-fa5b6f1db50d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
