<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add_Contact</name>
   <tag></tag>
   <elementGuidId>2e514c81-a884-4a21-9d64-ba362b2ef210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.entitydata181.entitydata269.entitydata271.entitydata4694 > span.entitydata270</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div/div[2]/div[5]/div[2]/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;dataGroupItemsGrid-contacts&quot;] >> internal:role=button[name=&quot;Add&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6a43e75-a1f8-4ba6-ab51-de4c82d07a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata270</value>
      <webElementGuid>f25a7a69-ea97-4550-a09a-b787efc3cd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>07cd8fc1-bb52-44da-8987-d51cdad334d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-entitydata&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;entitydata26&quot;]/div[@class=&quot;entitydata29 entitydata30&quot;]/div[5]/div[2]/div[@class=&quot;entitydata4691&quot;]/div[@class=&quot;entitydata4693&quot;]/button[@class=&quot;entitydata181 entitydata269 entitydata271 entitydata4694&quot;]/span[@class=&quot;entitydata270&quot;]</value>
      <webElementGuid>4a88c12b-aa7f-4ea6-86ef-463c021bba4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div/div[2]/div[5]/div[2]/div/div/button/span</value>
      <webElementGuid>dd74bce1-4c92-49e1-8e8d-bee1b274e9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Contact'])[1]/following::span[3]</value>
      <webElementGuid>4548d743-2a94-4aea-8606-1fc80529191a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data added'])[2]/preceding::span[3]</value>
      <webElementGuid>c4a2192c-8f04-469b-8897-f70bd707b21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emails'])[1]/preceding::span[3]</value>
      <webElementGuid>7597af4e-747d-4ec1-91c3-434ea817e395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/button/span</value>
      <webElementGuid>49ff1dc7-6179-4049-8868-a9bb536b0e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>7a433bb9-cdf5-4943-aec1-054844b8407f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
