<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillingAdd_Save</name>
   <tag></tag>
   <elementGuidId>abfb4ba1-abc6-4deb-a787-e5142dde20ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[contains(text(), 'Add Address')]//following::span[text()='Save'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.entitydata169.entitydata2602 > button.entitydata284.entitydata372.entitydata380.entitydata381 > span.entitydata373</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;data-group-collection-modal-save-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d78dfbec-74d5-4234-bf2d-6bb33f2fb3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata373</value>
      <webElementGuid>4f979c54-f260-4d06-b27c-36673b9f9396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>6356e50f-c3b6-43d0-bcfc-3431108c301f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;entitydata2608&quot;]/div[@class=&quot;entitydata2611 entitydata2609&quot;]/div[@class=&quot;entitydata2627 entitydata2612 entitydata2604 entitydata2613 entitydata2618 entitydata2621 entitydata2654 entitydata2628&quot;]/div[@class=&quot;entitydata169 entitydata2602&quot;]/button[@class=&quot;entitydata284 entitydata372 entitydata380 entitydata381&quot;]/span[@class=&quot;entitydata373&quot;]</value>
      <webElementGuid>1d825e2e-958d-4bae-b700-445dc030d1b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>23780d29-6170-4095-a3c0-3e7c4dadd127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Another'])[1]/following::span[2]</value>
      <webElementGuid>2d73bfc5-34c8-4a50-b4d5-25d2a7712665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[31]/following::span[3]</value>
      <webElementGuid>7f5efcfa-7c8a-477f-a98b-4227c429e457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/button[2]/span</value>
      <webElementGuid>49bbe8c4-3257-4c2c-bcf6-a99f0c30bebd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
