<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Billing_Add</name>
   <tag></tag>
   <elementGuidId>dd927cc6-464f-48f6-b713-4e420f0ee6f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Add' or . = 'Add')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.entitydata181.entitydata269.entitydata271.entitydata2546 > span.entitydata270</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;dataGroupItemsGrid-address&quot;] >> internal:role=button[name=&quot;Add&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a9be2ec-1338-41e9-adf0-b1530351158d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata270</value>
      <webElementGuid>7e62be1e-9e7c-45a7-b646-56c7a0f363d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>152f7d39-d5b0-44f0-a57d-aec5b73b7258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-entitydata&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;entitydata26&quot;]/div[@class=&quot;entitydata29 entitydata30&quot;]/div[4]/div[2]/div[@class=&quot;entitydata2543&quot;]/div[@class=&quot;entitydata2545&quot;]/button[@class=&quot;entitydata181 entitydata269 entitydata271 entitydata2546&quot;]/span[@class=&quot;entitydata270&quot;]</value>
      <webElementGuid>67095878-edfb-4645-ace4-8f6ebcf6520d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>7f2537b2-3307-4673-ab78-71f601454367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Address'])[1]/following::span[3]</value>
      <webElementGuid>f6434a3f-5fad-4bab-9db6-c33c4b6be994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data added'])[1]/preceding::span[5]</value>
      <webElementGuid>17bd30f7-8f57-4bcb-ba37-e516e0c0c9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::span[5]</value>
      <webElementGuid>8588d7d1-7542-46a8-890c-35a432af159e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>65d1be65-9885-44b4-80e2-19454da967a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div/div[2]/div[4]/div[2]/div/div/button/span</value>
      <webElementGuid>8a7c1ed8-4c5a-47cf-9d33-bf89a0f50dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/button/span</value>
      <webElementGuid>5b6a7e6c-d9e6-4859-918d-238654aab79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data added'])[1]/preceding::span[3]</value>
      <webElementGuid>6a617ae1-9b6e-4ab8-8149-bd62f980215d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::span[3]</value>
      <webElementGuid>3a2cc295-1135-4077-9091-5a289ab865e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
