<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contact_Save</name>
   <tag></tag>
   <elementGuidId>fc795989-05f6-451c-8754-1790e1521e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.entitydata66.entitydata4713 > button.entitydata181.entitydata269.entitydata277.entitydata278 > span.entitydata270</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Another'])[1]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;data-group-collection-modal-save-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0292a7c0-6a29-46b7-a2aa-f3bd26d75790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata270</value>
      <webElementGuid>ea0f8a1a-b0df-4171-94dc-f01bbb3cb1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>1accc294-4cd0-49b2-a586-64946c9de043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;entitydata4719&quot;]/div[@class=&quot;entitydata4722 entitydata4720&quot;]/div[@class=&quot;entitydata4736 entitydata4723 entitydata4715 entitydata4724 entitydata4729 entitydata4732 entitydata4763 entitydata4737&quot;]/div[@class=&quot;entitydata66 entitydata4713&quot;]/button[@class=&quot;entitydata181 entitydata269 entitydata277 entitydata278&quot;]/span[@class=&quot;entitydata270&quot;]</value>
      <webElementGuid>0bcfaa1a-5b04-422f-a310-cb66a7013c1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Another'])[1]/following::span[2]</value>
      <webElementGuid>086debcf-afb7-40a6-836a-7eb8513cb22b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[33]/following::span[3]</value>
      <webElementGuid>41b481ab-9d88-4272-9d93-e2070d3e332a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/button[2]/span</value>
      <webElementGuid>77d28af5-ec6d-483a-b0e5-7ca7b30901f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>8a973d4c-45be-44c1-badc-98b4ada23ee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
