<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date selection</name>
   <tag></tag>
   <elementGuidId>1c6c0329-8f88-4e96-8e64-bc3e938dc8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::p[25]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;19&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c107fecc-619a-4c94-b463-0b73c29b36c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata34 entitydata35 entitydata56</value>
      <webElementGuid>4cf0c7a3-45ae-4cff-9bd6-d6d212e2935a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>9e0777a8-bb7e-46e9-abf2-a709c6eeaf76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;entitydata261&quot;]/div[@class=&quot;entitydata2615 entitydata262 entitydata2626 entitydata2616&quot;]/div[@class=&quot;entitydata2643&quot;]/div[@class=&quot;entitydata2645&quot;]/div[@class=&quot;entitydata2667 entitydata2659&quot;]/div[1]/div[@class=&quot;entitydata2661&quot;]/div[4]/button[@class=&quot;entitydata181 entitydata172 entitydata2674&quot;]/span[@class=&quot;entitydata180&quot;]/p[@class=&quot;entitydata34 entitydata35 entitydata56&quot;]</value>
      <webElementGuid>8d4aa022-3fa4-44aa-a9a6-673bf14698e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::p[25]</value>
      <webElementGuid>5ee1629a-6537-44ec-ab99-b9276b52a341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::p[25]</value>
      <webElementGuid>ad1c8cf9-5ef3-41da-bfc8-e549713533dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19']/parent::*</value>
      <webElementGuid>c6611813-a2d9-4fc8-b35a-e981d4ebff92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/button/span/p</value>
      <webElementGuid>e6aa3db2-b682-4efa-95a4-5e2858c7ae43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '19' or . = '19')]</value>
      <webElementGuid>fd7af789-2278-4602-ab96-fe5ffe06b4e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
