<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date selection</name>
   <tag></tag>
   <elementGuidId>1c6c0329-8f88-4e96-8e64-bc3e938dc8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = '19' or . = '19')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;19&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>57834d5a-c548-4210-8e08-305ad4914fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata34 entitydata35 entitydata56</value>
      <webElementGuid>7a0b7c35-7116-4437-838a-2404c205011a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>6ee236ef-605e-4b4c-b36d-6e7f18dc717d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;entitydata261&quot;]/div[@class=&quot;entitydata1947 entitydata262 entitydata1958 entitydata1948&quot;]/div[@class=&quot;entitydata1975&quot;]/div[@class=&quot;entitydata1977&quot;]/div[@class=&quot;entitydata1999 entitydata1991&quot;]/div[1]/div[@class=&quot;entitydata1993&quot;]/div[4]/button[@class=&quot;entitydata181 entitydata172 entitydata2006&quot;]/span[@class=&quot;entitydata180&quot;]/p[@class=&quot;entitydata34 entitydata35 entitydata56&quot;]</value>
      <webElementGuid>21702351-4a5c-4a50-857c-d020b346bf6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '19' or . = '19')]</value>
      <webElementGuid>8fdcf7da-1619-4539-b420-319e689c0833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::p[25]</value>
      <webElementGuid>2199502d-b3ee-4bed-89fc-083e13fa0412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::p[25]</value>
      <webElementGuid>f999d6e7-e8d9-40f9-a741-95a957813300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19']/parent::*</value>
      <webElementGuid>93fa8271-587a-41f7-89c3-752459d2d0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/button/span/p</value>
      <webElementGuid>676a747c-cd74-4242-bc05-1f75e5820b0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
