<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Link</name>
   <tag></tag>
   <elementGuidId>f652b55e-bdef-4930-b3d8-6922d568fe95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.MuiTableCell-root.MuiTableCell-body.ass3086.MuiTableCell-sizeSmall > div.MuiButtonBase-root.MuiChip-root.ass3079.MuiChip-clickable > span.MuiChip-label.ass3080</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Link' or . = 'Link')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-radio-chip-link&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ca371e8-52e7-4f22-aa6d-e326651e2fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiChip-label ass3080</value>
      <webElementGuid>8d52f556-f76d-46cf-887d-8cc779f5f153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>b9874c10-795a-4614-9668-0c85f68ab4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDialog-root&quot;]/div[@class=&quot;MuiDialog-container MuiDialog-scrollPaper&quot;]/div[@class=&quot;MuiPaper-root MuiDialog-paper MuiDialog-paperScrollPaper MuiDialog-paperWidthXl MuiDialog-paperFullWidth MuiPaper-elevation24 MuiPaper-rounded&quot;]/div[@class=&quot;MuiDialogContent-root ass1030&quot;]/div[@class=&quot;ass1027&quot;]/div[@class=&quot;ass1029&quot;]/div[@class=&quot;MuiPaper-root MuiAccordion-root ass2199 Mui-expanded ass2204 MuiAccordion-rounded MuiPaper-elevation1 MuiPaper-rounded&quot;]/div[@class=&quot;MuiCollapse-root MuiCollapse-entered&quot;]/div[@class=&quot;MuiCollapse-wrapper&quot;]/div[@class=&quot;MuiCollapse-wrapperInner&quot;]/div[1]/div[@class=&quot;MuiAccordionDetails-root ass2203&quot;]/div[@class=&quot;ass3075&quot;]/div[@class=&quot;MuiTableContainer-root ass3074&quot;]/table[@class=&quot;MuiTable-root&quot;]/tbody[@class=&quot;MuiTableBody-root&quot;]/tr[@class=&quot;MuiTableRow-root ass1134 ass3082 MuiTableRow-hover&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body ass3086 MuiTableCell-sizeSmall&quot;]/div[@class=&quot;MuiButtonBase-root MuiChip-root ass3079 MuiChip-clickable&quot;]/span[@class=&quot;MuiChip-label ass3080&quot;]</value>
      <webElementGuid>40e144bd-5ba0-47ac-bb39-ddf10cb5dd9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Link' or . = 'Link')]</value>
      <webElementGuid>bddf5aee-84a4-4945-8055-0e0d7107b4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Type'])[2]/following::span[4]</value>
      <webElementGuid>59cc23ec-5616-421e-9b1c-a0b6299249e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/following::span[4]</value>
      <webElementGuid>522a513c-4947-4cc6-a1e8-65abc83e9b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chaitrali Gajjar'])[1]/preceding::span[4]</value>
      <webElementGuid>b389b7b3-25eb-412a-a689-5d24258e7bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exact Match'])[1]/preceding::span[4]</value>
      <webElementGuid>5f2dbf9d-77dc-429c-8a7a-0f5e3e18c5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link']/parent::*</value>
      <webElementGuid>688fbad8-07df-42c7-be8e-91dc279382d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/span[2]</value>
      <webElementGuid>9196e24c-ff2b-4394-9ca1-24b14b708e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
