<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search</name>
   <tag></tag>
   <elementGuidId>2a2d44b2-8e2e-4df9-8c93-5e0ec668c9ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.jou730</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Search' or . = 'Search')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;search-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>afc46c4e-fa0c-48dd-ba91-3d0b1ce8659f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jou730</value>
      <webElementGuid>edc4c43c-24a3-4de9-b1aa-54467d2d13e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>6c7b64fe-4070-46e1-91e9-7385c8cd2046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-journey&quot;)/div[1]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;jou494&quot;]/div[@class=&quot;jou497 jou498&quot;]/div[@class=&quot;jou602 jou603&quot;]/div[@class=&quot;jou534&quot;]/button[@class=&quot;jou567 jou729 jou737 jou738&quot;]/span[@class=&quot;jou730&quot;]</value>
      <webElementGuid>a19d536e-06a1-459c-96cb-f065692c70b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>74861fe8-8ff8-401c-9285-5a02276997c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[4]/following::span[1]</value>
      <webElementGuid>b81842b7-0e4d-4399-97ac-2aaf85884b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>9fd1b9ba-ab0f-484d-913b-67de7fab8104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-journey']/div/div/div/div/div/div/div[2]/div[2]/div[2]/button/span</value>
      <webElementGuid>2f6ef507-547d-41ce-8a21-d3f93df0e35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button/span</value>
      <webElementGuid>1d0f7178-1d1f-419d-8ce5-817239e94ad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
