<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save_Contact</name>
   <tag></tag>
   <elementGuidId>f2a441c4-1b41-4d66-aa73-c58d940ffeed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.entitydata169.entitydata2700 > button.entitydata284.entitydata372.entitydata380.entitydata381</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and @data-testid = 'data-group-collection-modal-save-button' and (text() = 'Save' or . = 'Save')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;data-group-collection-modal-save-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a0bd390-8549-4e50-b622-a035b883d818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata284 entitydata372 entitydata380 entitydata381</value>
      <webElementGuid>322553ed-0253-4363-81c2-6b5ad3c04f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>604d434e-eaea-43a1-af2d-642ae46cbea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d41ebd7-fcd0-45b8-9e8d-037aebaeed0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>data-group-collection-modal-save-button</value>
      <webElementGuid>851e57cb-ad56-4f8f-9da8-d5001bc8dfcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>c858fac1-a67f-4569-9f2c-a83844ee2487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;entitydata2706&quot;]/div[@class=&quot;entitydata2709 entitydata2707&quot;]/div[@class=&quot;entitydata2723 entitydata2710 entitydata2702 entitydata2711 entitydata2716 entitydata2719 entitydata2750 entitydata2724&quot;]/div[@class=&quot;entitydata169 entitydata2700&quot;]/button[@class=&quot;entitydata284 entitydata372 entitydata380 entitydata381&quot;]</value>
      <webElementGuid>304882a3-575b-44f3-a95b-dc1aff96c297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @data-testid = 'data-group-collection-modal-save-button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>9074d0ed-6d7d-4e74-9a58-998e668fc1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Another'])[1]/following::button[1]</value>
      <webElementGuid>354647e1-d0bc-4760-acaa-64bbc4be7c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[33]/following::button[2]</value>
      <webElementGuid>960f9443-dabf-4a3f-a54a-92fa049ec6c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[57]</value>
      <webElementGuid>9635a27c-a08a-44da-bb32-279f8286f432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/button[2]</value>
      <webElementGuid>b32b62bc-b6d0-4065-9550-062bce2c9490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
