<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Billing_Add</name>
   <tag></tag>
   <elementGuidId>427921aa-bd46-4b3e-a005-62387f18a636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.entitydata181.entitydata269.entitydata271.entitydata1788 > span.entitydata270</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[contains(text(), 'Add Address')]//following::span[text()='Add'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;dataGroupItemsGrid-address&quot;] >> internal:role=button[name=&quot;Add&quot;(.//*[contains(text(), 'Add Address')]//following::span[text()='Add'])[1]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1362ccef-5ca3-4795-9da5-7b27377de959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata270</value>
      <webElementGuid>03774aed-3564-4106-9e36-bae0e1a2615e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>23f7a664-f52a-42dd-a784-0b1dc1233a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-entitydata&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;entitydata26&quot;]/div[@class=&quot;entitydata29 entitydata30&quot;]/div[4]/div[2]/div[@class=&quot;entitydata1785&quot;]/div[@class=&quot;entitydata1787&quot;]/button[@class=&quot;entitydata181 entitydata269 entitydata271 entitydata1788&quot;]/span[@class=&quot;entitydata270&quot;]</value>
      <webElementGuid>6bfb7bd8-15db-4126-9e5f-d270d255f525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>68c56577-4111-473b-9d18-ebbf94ab83c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Address'])[1]/following::span[3]</value>
      <webElementGuid>99ea304f-f06d-47d5-948a-84bf2593534e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data added'])[1]/preceding::span[5]</value>
      <webElementGuid>131c8bc4-a9a7-4076-92d8-a2f917fbfac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::span[5]</value>
      <webElementGuid>6996046d-82e0-4a85-b902-4ee8bae0295c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>15412c77-6696-4305-8764-e8f18ddf5b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div/div[2]/div[4]/div[2]/div/div/button/span</value>
      <webElementGuid>d48c5ff9-e40d-4370-aa0f-1be54d2f14c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/button/span</value>
      <webElementGuid>8c9f8cd4-5615-4d3a-b0c2-13c4474043cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
