<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>d52400f3-a3b1-4172-948f-2a378d5d0c29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and @data-testid = 'data-group-collection-modal-save-button' and (text() = 'Save' or . = 'Save')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.entitydata169.entitydata2654 > button.entitydata284.entitydata372.entitydata380.entitydata381</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;data-group-collection-modal-save-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>27ffc8fb-fea6-4256-89e0-fc985f8b6c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata284 entitydata372 entitydata380 entitydata381</value>
      <webElementGuid>3b6b782a-4fc9-4f39-af74-c7533bfe824c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>09f3b5a3-5808-479f-929c-76a4a1c84b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d09b183b-4d99-4d36-8fee-e93ca20b6349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>data-group-collection-modal-save-button</value>
      <webElementGuid>081637cc-9a6e-44c9-9ac7-671a7bcd75de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>153ec850-40c9-41ab-b958-73bed5d9f3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;entitydata2660&quot;]/div[@class=&quot;entitydata2663 entitydata2661&quot;]/div[@class=&quot;entitydata2679 entitydata2664 entitydata2656 entitydata2665 entitydata2670 entitydata2673 entitydata2706 entitydata2680&quot;]/div[@class=&quot;entitydata169 entitydata2654&quot;]/button[@class=&quot;entitydata284 entitydata372 entitydata380 entitydata381&quot;]</value>
      <webElementGuid>16efe59c-6281-4ea0-b80b-cd27ef91cb56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @data-testid = 'data-group-collection-modal-save-button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>e2b36527-c55f-44fb-846d-f94d74a4a9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Another'])[1]/following::button[1]</value>
      <webElementGuid>2d356330-f14e-48a9-aa7a-2d3025510750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[31]/following::button[2]</value>
      <webElementGuid>be8dbcf1-66ee-448f-865c-da678ea07eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[59]</value>
      <webElementGuid>4ccb477a-20dc-4993-8ba7-0eff1bbaf1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/button[2]</value>
      <webElementGuid>0501ac2a-4a39-48a9-b86e-c54e7b4ca4dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
