<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AddressAdd Address</name>
   <tag></tag>
   <elementGuidId>72ad8377-7577-4ecb-8cef-d2707b3558fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.entitydata31.entitydata265</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@data-testid = 'fen-header-address' and (text() = 'AddressAdd Address' or . = 'AddressAdd Address')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-header-address&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>537757c8-70f9-4a4f-995e-49d0e00f4fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata31 entitydata265</value>
      <webElementGuid>f1848132-3c51-40d0-a2c4-44342c2fb3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>fen-header-address</value>
      <webElementGuid>caf2e526-866e-4318-a29b-08e4fb8af761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AddressAdd Address</value>
      <webElementGuid>4f0c42ce-5a93-44c4-adfd-cf7fa6f15ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-entitydata&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;entitydata26&quot;]/div[@class=&quot;entitydata29 entitydata30&quot;]/div[4]/div[@class=&quot;entitydata31 entitydata265&quot;]</value>
      <webElementGuid>281ae182-ed9e-4e39-a381-111075440b7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@data-testid = 'fen-header-address' and (text() = 'AddressAdd Address' or . = 'AddressAdd Address')]</value>
      <webElementGuid>f96189bb-0966-446e-9343-e1a09c483a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal'])[1]/following::div[2]</value>
      <webElementGuid>2e0daa07-02b5-48b6-964b-1ea4454c25c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[1]/following::div[4]</value>
      <webElementGuid>e117f6b2-e5cd-4b82-bc72-5114e0fde03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div/div[2]/div[4]/div</value>
      <webElementGuid>9a496790-f28e-4582-8828-23de07e13017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>e2b72758-25b4-4ec8-864d-b3eaf0da3772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
