<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname(English Name)_properties.cont_c09b61</name>
   <tag></tag>
   <elementGuidId>40736c04-28ec-4196-b958-17dc825e1566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fenx-80479</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'properties.contact_lastName' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Surname (English Name)*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95b0339f-f983-40b2-aa59-80ba6aaa1496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3fbbe8d2-445e-47ca-8418-787734797c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>properties.contact_lastName</value>
      <webElementGuid>ef7d8096-796a-4b31-abd8-3cef244df5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a4943fd-12b5-468f-9160-ac9f75ecf55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata268 entitydata252 entitydata269 entitydata253</value>
      <webElementGuid>cc014af5-acef-41a3-9fc7-0b0d769df167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fenx-80479</value>
      <webElementGuid>9af4497e-fafc-4ae0-a9ac-aaa35cd202cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fenx-80479&quot;)</value>
      <webElementGuid>72c6cbfe-597d-4bcd-8eee-5c9a72de9706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'properties.contact_lastName' and @type = 'text']</value>
      <webElementGuid>b9f345cf-ddc1-4456-8c6e-fb2176e14c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fenx-80479']</value>
      <webElementGuid>239bdabd-7389-4061-8d6a-81ff642589a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>f98929b4-1a34-43ab-8a7d-0a9c76867b14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
