<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TenantName</name>
   <tag></tag>
   <elementGuidId>be39ba75-845d-4a79-a67e-11e4ac44f856</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tenantName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tenantName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tenantName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18cd81c9-ac35-46a8-bfe8-124274f0ea7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tenantName</value>
      <webElementGuid>c1ac6f45-57a1-474c-a2ac-6725a1d95739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3e4d736-8fc6-422b-b60f-7d8308986133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4dd2346c-0279-4e64-9ad9-6ee46492c1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The TenantName field is required.</value>
      <webElementGuid>957ec319-1f4b-4b5a-9e55-d997991c86d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TenantName</value>
      <webElementGuid>80e0fdf0-c010-4738-89ba-3b61ae2c0036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tenantName&quot;)</value>
      <webElementGuid>4d61bfe4-6ed5-43f8-ba93-b1be337c1f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tenantName']</value>
      <webElementGuid>dbc3db59-5939-4d56-9beb-2c92c9c1e2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>5ff98da7-9459-4429-9ffd-4ac8bbf99167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tenantName' and @type = 'text' and @name = 'TenantName']</value>
      <webElementGuid>934b523b-2fc3-4b9f-bd87-87d64fadd5d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
