<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Are there Other hits_properties.other_bb14e1</name>
   <tag></tag>
   <elementGuidId>760fd3a0-95e7-43a5-b8eb-78cc2874579a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fenx-27888</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'properties.otherScreening' and @placeholder = ' - select value -' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-dropdown-are-there-other-hits\?&quot;] >> internal:attr=[placeholder=&quot; - select value -&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19372f10-673d-4c2d-bc3d-f640ddb92c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ecc66b1d-accc-4f9a-8098-5ac9e76102ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dbde3de7-401f-477b-9d76-38b6e78ce0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>properties.otherScreening</value>
      <webElementGuid>e3d2cedb-eb73-4d9e-9a1a-fe0a375dc68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> - select value -</value>
      <webElementGuid>1c264ce8-10b1-4b50-a7db-62442c88cafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e793ce76-4396-431a-b7af-ef05b5a11ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiAutocomplete-input MuiAutocomplete-inputFocused MuiInputBase-inputAdornedEnd MuiOutlinedInput-inputAdornedEnd MuiInputBase-inputMarginDense MuiOutlinedInput-inputMarginDense</value>
      <webElementGuid>20c1c6d8-69fb-4c2b-8d3b-f3fcbf0f8005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>4e297c85-3bc1-4d28-b62a-4602ef4bdcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>209d5566-fb79-4d65-84cf-acb336787314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1dd1a299-f962-4423-b1d8-2872d3f6171b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fenx-27888</value>
      <webElementGuid>55a977de-399c-474f-9531-96cd153d2623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>fenx-27888-popup</value>
      <webElementGuid>e2f5e656-4d7d-405e-ad52-848e17493db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>fenx-27888-option-0</value>
      <webElementGuid>e29e8ace-bd98-442e-ba52-c32c45772b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fenx-27888&quot;)</value>
      <webElementGuid>40e71205-5ded-4202-9ddc-551c3b6c0827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'properties.otherScreening' and @placeholder = ' - select value -' and @type = 'text']</value>
      <webElementGuid>c4e44b9c-6290-4ad0-9082-523d696dc613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fenx-27888']</value>
      <webElementGuid>3428d526-bd4e-4a89-8489-7cf6e7ff6f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/div[2]/div/input</value>
      <webElementGuid>36fa2848-6bc8-4b1d-9673-8fce6b59754d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
