<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Link</name>
   <tag></tag>
   <elementGuidId>43dd1fde-434f-4d2f-a445-5f8563af5b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Link' or . = 'Link')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.portalTenant144</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;toolbar-link-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d13249a6-78d4-4cf1-861f-1554aaa618d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portalTenant144</value>
      <webElementGuid>53c48ba2-756b-48e8-a050-a411961918a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Link</value>
      <webElementGuid>13bbf8d2-d2d4-4d56-93cc-ec3350b7d647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-portal-tenant&quot;)/div[1]/div[1]/div[@class=&quot;portalTenant26&quot;]/div[@class=&quot;portalTenant29 portalTenant30&quot;]/div[@class=&quot;portalTenant632&quot;]/div[@class=&quot;portalTenant214 portalTenant221&quot;]/div[@class=&quot;portalTenant66&quot;]/button[@class=&quot;portalTenant172 portalTenant143 portalTenant148 portalTenant149&quot;]/span[@class=&quot;portalTenant144&quot;]</value>
      <webElementGuid>f116e314-7d25-4661-b11b-b1a25a0fcc34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Link' or . = 'Link')]</value>
      <webElementGuid>53fde97e-8b4e-4422-81c2-cf867915888b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outreach Users'])[1]/following::span[1]</value>
      <webElementGuid>2b5db53b-836b-416d-a685-7301c1f3bd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Portal User'])[2]/following::span[1]</value>
      <webElementGuid>d803587a-8446-4c58-bb61-ea4e6fa0d676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::span[5]</value>
      <webElementGuid>395e9456-19d2-440e-b0d2-f491baabcf2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data added'])[1]/preceding::span[8]</value>
      <webElementGuid>f21cd325-7283-43ad-95b3-ca29bd3125fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Link']/parent::*</value>
      <webElementGuid>b1c9caf1-cc88-420f-bfbe-773a97ae5631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-portal-tenant']/div/div/div/div[2]/div/div[2]/div[3]/button/span</value>
      <webElementGuid>923a9e7b-1a0c-455f-bc3d-41beca62be66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/button/span</value>
      <webElementGuid>cad4a43e-ad6f-486d-8e84-e0d6a82fbacc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
