<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Complete</name>
   <tag></tag>
   <elementGuidId>71eaaa2b-5ae2-490e-ba29-76f99a452ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.portalTenant66.portalTenant647 > button.portalTenant172.portalTenant143.portalTenant151.portalTenant152 > span.portalTenant144</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Complete' or . = 'Complete')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-button-complete&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>264c7833-3f16-44aa-844f-822666ab0a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>portalTenant144</value>
      <webElementGuid>2e069e3f-f872-49db-b17b-de17ae1104db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complete</value>
      <webElementGuid>1d8ca13f-d486-4675-a9e9-69348147a579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;portalTenant653&quot;]/div[@class=&quot;portalTenant656 portalTenant654&quot;]/div[@class=&quot;portalTenant676 portalTenant657 portalTenant649 portalTenant658 portalTenant663 portalTenant666 portalTenant703 portalTenant677&quot;]/div[@class=&quot;portalTenant66 portalTenant647&quot;]/button[@class=&quot;portalTenant172 portalTenant143 portalTenant151 portalTenant152&quot;]/span[@class=&quot;portalTenant144&quot;]</value>
      <webElementGuid>442b5f5e-449a-48e0-ac37-1239dc450597</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Complete' or . = 'Complete')]</value>
      <webElementGuid>4250c16a-0de6-4fee-9353-9b7629a3f61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cg@gmail.com'])[3]/following::span[1]</value>
      <webElementGuid>1be3ecca-d45c-41bd-8ece-40686a47cbee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorised Signatory'])[2]/following::span[1]</value>
      <webElementGuid>b5c644c4-6453-4392-9e13-8f80337ce629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/button/span</value>
      <webElementGuid>8a9b639e-b7fe-4d50-bb89-62b387980ef1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
