<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Client Acceptance</name>
   <tag></tag>
   <elementGuidId>1d0a49ce-d6d1-40b0-be5a-17981d3b67d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fep34.fep202.fep204.fep57</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@data-testid = 'fen-link-client-acceptance' and @href = '/journey/cad29993-d318-4b7f-8ef3-a633785b9c84' and (text() = 'Client Acceptance' or . = 'Client Acceptance')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-link-client-acceptance&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ddc9d44a-baab-4213-afed-f9118b5fa199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fep34 fep202 fep204 fep57</value>
      <webElementGuid>4bfd2fa9-6710-46d7-aed9-cbda48bad575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>fen-link-client-acceptance</value>
      <webElementGuid>08918896-768f-42ac-86ee-f55d3860fc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/journey/cad29993-d318-4b7f-8ef3-a633785b9c84</value>
      <webElementGuid>cb30f7b4-f5ab-4ca2-92d7-1e1d03a5e070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client Acceptance</value>
      <webElementGuid>77f88c17-2ce6-4129-a136-6ce291ced184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-entity-profile&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;fep25&quot;]/div[@class=&quot;fep27 fep29&quot;]/div[@class=&quot;fep232&quot;]/div[@class=&quot;fep1091&quot;]/div[@class=&quot;fep1001 fep1090&quot;]/table[@class=&quot;fep1002&quot;]/tbody[@class=&quot;fep1030&quot;]/tr[@class=&quot;fep1008 fep1038 fep1031 fep1010&quot;]/td[@class=&quot;fep1013 fep1015 fep1035 fep1017&quot;]/a[@class=&quot;fep34 fep202 fep204 fep57&quot;]</value>
      <webElementGuid>a2dbb8f7-e38a-447d-a9d1-20c3a6f73071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@data-testid = 'fen-link-client-acceptance' and @href = '/journey/cad29993-d318-4b7f-8ef3-a633785b9c84' and (text() = 'Client Acceptance' or . = 'Client Acceptance')]</value>
      <webElementGuid>e79ad8f5-660c-47c7-90cb-a492bf970313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journey Owner'])[1]/following::a[1]</value>
      <webElementGuid>361ece8d-1ca0-42d6-8c29-2e38008e3a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Started On'])[1]/following::a[1]</value>
      <webElementGuid>52d25b58-35dc-4032-b386-afae9e85454f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Normal'])[1]/preceding::a[1]</value>
      <webElementGuid>40b02e96-6f02-4293-9c70-eada75cd3daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/preceding::a[1]</value>
      <webElementGuid>b7338fdc-31c9-4c35-a9f0-7c32142db534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Client Acceptance']/parent::*</value>
      <webElementGuid>c10a94c2-045c-4cb3-85db-479d377e5efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entity-profile']/div/div/div/div/div[2]/div[3]/div/div[3]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>ba191540-d529-4f45-9416-0d3fcb4e2fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Client Acceptance')]</value>
      <webElementGuid>2c71fa5a-e766-4866-a279-4b3725a8fbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/journey/cad29993-d318-4b7f-8ef3-a633785b9c84')]</value>
      <webElementGuid>7f6a4408-5900-4474-8fc2-c5fc39d19afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>bb4f6087-b75d-4b70-8a4f-fdb6b525e9e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
