<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Journeys</name>
   <tag></tag>
   <elementGuidId>5317bc19-6dcf-4bf9-9722-0397c23a24ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Journeys' or . = 'Journeys')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-tab-journeys&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>62d5a64e-fd8c-45d0-90e5-1a30aa3c483f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fep264</value>
      <webElementGuid>8d16be31-876d-413d-bb0c-64376cd96ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Journeys</value>
      <webElementGuid>63c085ed-8ab9-43fa-b0ef-1e46765f688c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-entity-profile&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;fep25&quot;]/div[@class=&quot;fep27 fep29&quot;]/div[@class=&quot;fep244&quot;]/div[@class=&quot;fep249 fep251&quot;]/div[@class=&quot;fep246&quot;]/button[@class=&quot;fep84 fep255 fep257&quot;]/span[@class=&quot;fep264&quot;]</value>
      <webElementGuid>a71dbffb-6b9d-4bc9-b26f-147cb2cf9af9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Journeys' or . = 'Journeys')]</value>
      <webElementGuid>46fea17b-1a7f-4d06-92ec-517d10c2da5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/following::span[2]</value>
      <webElementGuid>5589cbf7-97b3-48d5-8f46-df6df6caa7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All'])[1]/following::span[8]</value>
      <webElementGuid>bc2200e3-f0b5-4359-967e-98a17fa76cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scheduled Reviews'])[1]/preceding::span[4]</value>
      <webElementGuid>ad14e03b-0473-4788-93b1-041943b76a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data'])[1]/preceding::span[6]</value>
      <webElementGuid>2ec6bd0b-2715-4f68-9182-64809b867a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Journeys']/parent::*</value>
      <webElementGuid>f3d86477-b4c6-4519-9978-0aa079bd23e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entity-profile']/div/div/div/div/div[2]/div[2]/div[3]/div/button[2]/span</value>
      <webElementGuid>f076899c-3ebf-4b91-9621-cf27bbbf7443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]/span</value>
      <webElementGuid>26a42cb9-9d41-4985-8635-76f88310cd9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
