<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BI_RM</name>
   <tag></tag>
   <elementGuidId>4dbfb9c0-a406-4922-b3c9-7f6e91c37bde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6.jou4198.jou4422.jou4210</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='single-spa-application:@fenx/ui-journey']/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Business InformationRelationship Manager$/ >> h6</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>d0442692-4501-400d-81a1-3f110c27073c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jou4198 jou4422 jou4210</value>
      <webElementGuid>b53022f3-4fed-4484-a981-d33cb41369eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Relationship Manager</value>
      <webElementGuid>9d5efb96-e873-4c43-842f-3d6601c9d061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:@fenx/ui-journey&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;jou4189 jou4188&quot;]/div[@class=&quot;jou4191 jou4193&quot;]/div[@class=&quot;jou4186&quot;]/div[@class=&quot;jou4365&quot;]/div[@class=&quot;jou4369 jou4370&quot;]/div[1]/div[@class=&quot;jou4416 jou4415 jou4410&quot;]/div[@class=&quot;jou4411&quot;]/div[@class=&quot;jou4418&quot;]/div[@class=&quot;jou4419&quot;]/h6[@class=&quot;jou4198 jou4422 jou4210&quot;]</value>
      <webElementGuid>60f405fc-339e-4e41-909e-800688835f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-journey']/div/div/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/h6</value>
      <webElementGuid>34427661-a557-4f1b-af6c-9e23ca2525fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Information'])[1]/following::h6[1]</value>
      <webElementGuid>8e097832-1ab5-4a70-9b07-39c30a6ca47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture Request Details'])[1]/following::h6[1]</value>
      <webElementGuid>c7580cc8-e23b-4b82-8a17-e177062643bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link Portal User'])[1]/preceding::h6[1]</value>
      <webElementGuid>7c99fcaf-8bf0-4e22-8f1e-f1203177cbbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship Manager'])[2]/preceding::h6[1]</value>
      <webElementGuid>dda0d5b0-895e-496a-acf6-4e20b493111d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Relationship Manager']/parent::*</value>
      <webElementGuid>9b06b9d0-d8bf-481c-bd8c-fdfbbf7a7d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h6</value>
      <webElementGuid>7ed9e632-f1a8-4b27-b004-d29cc3c98d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Relationship Manager' or . = 'Relationship Manager')]</value>
      <webElementGuid>e30b374c-ba81-4aa1-a642-6c0b2087680a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
