<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillingAdd_Save</name>
   <tag></tag>
   <elementGuidId>fadabf92-c651-402a-a27f-fcfdd1a1b1a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.entitydata66.entitydata7388 > button.entitydata181.entitydata269.entitydata277.entitydata278 > span.entitydata270</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Another'])[1]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;data-group-collection-modal-save-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>021c6d8f-ab0d-42ba-bb83-583ef9c6a23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata270</value>
      <webElementGuid>ebd618b0-a638-48ff-aff7-834ebdfe6543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>9c8a8354-e152-4355-acce-3de181515d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;entitydata7394&quot;]/div[@class=&quot;entitydata7397 entitydata7395&quot;]/div[@class=&quot;entitydata7413 entitydata7398 entitydata7390 entitydata7399 entitydata7404 entitydata7407 entitydata7440 entitydata7414&quot;]/div[@class=&quot;entitydata66 entitydata7388&quot;]/button[@class=&quot;entitydata181 entitydata269 entitydata277 entitydata278&quot;]/span[@class=&quot;entitydata270&quot;]</value>
      <webElementGuid>f1813586-437a-4238-8638-2bb4b49f2ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Another'])[1]/following::span[2]</value>
      <webElementGuid>bc8d7d90-77f8-48f2-b466-9bfd1583976a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[31]/following::span[3]</value>
      <webElementGuid>a9dd3af3-ef54-437c-9cc2-c2d68020d9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/button[2]/span</value>
      <webElementGuid>51832452-6020-436e-8826-ee3cf2f8c90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>5fc184b2-f353-450a-b66b-4667c650fa03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
