<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Country of incorporation</name>
   <tag></tag>
   <elementGuidId>e48b5b62-308e-431c-a660-569e478ae0dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fenx-63469</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fenx-63469']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;fen-dropdown-country-of-incorporation-\/-establishment&quot;] >> internal:attr=[placeholder=&quot; - select value -&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a7792fb-cf9a-47f6-aa10-678f8730d601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>22349397-e895-4c4e-abfc-a7561bbebe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6ea31e18-aa84-414e-9f9f-83f6731b2041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>properties.ClientCountryOfIncorporation</value>
      <webElementGuid>ddd7c0d3-39b3-4791-88ec-461bc12ada9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> - select value -</value>
      <webElementGuid>a885b35d-448a-477f-bfb6-6412160b36ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04c21462-8874-47e2-992d-466e58d751b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>entitydata165 entitydata149 entitydata100 entitydata101 entitydata170 entitydata153 entitydata166 entitydata150</value>
      <webElementGuid>aeb31170-9435-49a7-837c-81fb4eecb246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>0506bef5-e489-4e31-a6ac-fae1b769f2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ccd57ef1-9cdc-45a2-890c-b9bf4213448e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1dde5064-13d1-45c9-8c67-e319dcecd020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fenx-63469</value>
      <webElementGuid>ea5d43e8-6432-4aaf-9e6a-1c7aa71cc47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>fenx-63469-popup</value>
      <webElementGuid>83a4e7ed-0b4f-4919-87a5-c3efaca90773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>fenx-63469-option-0</value>
      <webElementGuid>6f4b25f4-33d4-4e34-a567-f909fe2c5662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fenx-63469&quot;)</value>
      <webElementGuid>0b81f185-d608-4d29-8df7-bea6c7bec9bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fenx-63469']</value>
      <webElementGuid>8c3f8db2-defb-44eb-a3d0-93a99983e624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:@fenx/ui-entitydata']/div/div/div/div/div/div[2]/div[3]/div[2]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>e9b4405f-da86-4881-9632-f7cb23a935a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>50792cf9-155c-4e98-8bd7-126cb6f24333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'properties.ClientCountryOfIncorporation' and @placeholder = ' - select value -' and @type = 'text' and @id = 'fenx-63469']</value>
      <webElementGuid>11022944-4cb5-4e18-8cf6-8373dcd819fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
